import style from '../styles/privacy.module.css'

const Privacy = () => {
    return (
        <>
            
            <div className={style.containerText}>
            <h1 style={{ marginTop: 100 }}>Página de Politica de privacidad</h1>
                <p>DATOS IDENTIFICATIVOS: En cumplimiento con el deber de información recogido en artículo 10 de la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y del Comercio Electrónico, a continuación se reflejan los siguientes datos: la empresa titular de dominio web es Paula Noriega Fernández<span id="more-352"></span> (en adelante ABSCISA Ingeniería Geomática y Topográfica), con domicilio a estos efectos en Calle Margarita 3, 45008 Toledo número de C.I.F.: 10904600R  de alta en el Régimen Especial de Trabajadores por Cuenta Propia o Autónomos. Correo electrónico de contacto: <a href="mailto:info@abscisaingenieria.com">info@abscisaingenieria.com</a></p>
                <p>USUARIOS: El acceso y/o uso de este portal de ABSCISA Ingeniería Geomática y Topográfica atribuye la condición de USUARIO, que acepta, desde dicho acceso y/o uso, las Condiciones Generales de Uso aquí reflejadas. Las citadas Condiciones serán de aplicación independientemente de las Condiciones Generales de Contratación que en su caso resulten de obligado cumplimiento.</p>
                <p>USO DEL PORTAL: www.abscisaingenieria.com proporciona el acceso a multitud de informaciones, servicios, programas o datos (en adelante, «los contenidos») en Internet pertenecientes a ABSCISA Ingeniería Geomática y Topográfica o a sus licenciantes a los que el USUARIO pueda tener acceso. El USUARIO asume la responsabilidad del uso del portal. Dicha responsabilidad se extiende al registro que fuese necesario para acceder a determinados servicios o contenidos. En dicho registro el USUARIO será responsable de aportar información veraz y lícita. Como consecuencia de este registro, al USUARIO se le puede proporcionar una contraseña de la que será responsable, comprometiéndose a hacer un uso diligente y confidencial de la misma. El USUARIO se compromete a hacer un uso adecuado de los contenidos y servicios (como por ejemplo servicios de chat, foros de discusión o grupos de noticias) que ABSCISA Ingeniería Geomática y Topográfica ofrece a través de su portal y con carácter enunciativo pero no limitativo, a no emplearlos para (i) incurrir en actividades ilícitas, ilegales o contrarias a la buena fe y al orden público; (ii) difundir contenidos o propaganda de carácter racista, xenófobo, pornográfico-ilegal, de apología del terrorismo o atentatorio contra los derechos humanos; (iii) provocar daños en los sistemas físicos y lógicos de ABSCISA Ingeniería Geomática y Topográfica , de sus proveedores o de terceras personas, introducir o difundir en la red virus informáticos o cualesquiera otros sistemas físicos o lógicos que sean susceptibles de provocar los daños anteriormente mencionados; (iv) intentar acceder y, en su caso, utilizar las cuentas de correo electrónico de otros usuarios y modificar o manipular sus mensajes. ABSCISA Ingeniería Geomática y Topográfica se reserva el derecho de retirar todos aquellos comentarios y aportaciones que vulneren el respeto a la dignidad de la persona, que sean discriminatorios, xenófobos, racistas, pornográficos, que atenten contra la juventud o la infancia, el orden o la seguridad pública o que, a su juicio, no resultaran adecuados para su publicación. En cualquier caso, ABSCISA Ingeniería Geomática y Topográfica no será responsable de las opiniones vertidas por los usuarios a través de los foros, chats, u otras herramientas de participación.</p>
                <p>PROPIEDAD INTELECTUAL E INDUSTRIAL: ABSCISA Ingeniería Geomática y Topográfica por sí o como cesionaria, es titular de todos los derechos de propiedad intelectual e industrial de su página web, así como de los elementos contenidos en la misma (a título enunciativo, imágenes, sonido, audio, vídeo, software o textos; marcas o logotipos, combinaciones de colores, estructura y diseño, selección de materiales usados, programas de ordenador necesarios para su funcionamiento, acceso y uso, etc.), titularidad de ABSCISA Ingeniería Geomática y Topográfica o bien de sus licenciantes. Todos los derechos reservados. En virtud de lo dispuesto en los artículos 8 y 32.1, párrafo segundo, de la Ley de Propiedad Intelectual, quedan expresamente prohibidas la reproducción, la distribución y la comunicación pública, incluida su modalidad de puesta a disposición, de la totalidad o parte de los contenidos de esta página web, con fines comerciales, en cualquier soporte y por cualquier medio técnico, sin la autorización de ABSCISA Ingeniería Geomática y Topográfica. El USUARIO se compromete a respetar los derechos de Propiedad Intelectual e Industrial titularidad de ABSCISA Ingeniería Geomática y Topográfica del sitio web. Podrá visualizar los elementos del portal e incluso imprimirlos, copiarlos y almacenarlos en el disco duro de su ordenador o en cualquier otro soporte físico siempre y cuando sea, única y exclusivamente, para su uso personal y privado. El USUARIO deberá abstenerse de suprimir,  alterar, eludir o manipular cualquier dispositivo de protección o sistema de seguridad que estuviera instalado en el las páginas de ABSCISA Ingeniería Geomática y Topográfica del sitio web.</p>
                <p>EXCLUSIÓN DE GARANTÍAS Y RESPONSABILIDAD: ABSCISA Ingeniería Geomática y Topográfica no se hace responsable, en ningún caso, de los daños y perjuicios de cualquier naturaleza que pudieran ocasionar, a título enunciativo: errores u omisiones en los contenidos, falta de disponibilidad del portal o la transmisión de virus o programas maliciosos o lesivos en los contenidos, a pesar de haber adoptado todas las medidas tecnológicas necesarias para evitarlo.</p>
                <p>MODIFICACIONES: ABSCISA Ingeniería Geomática y Topográfica se reserva el derecho de efectuar sin previo aviso las modificaciones que considere oportunas en su portal, pudiendo cambiar, suprimir o añadir tanto los contenidos y servicios que se presten a través de la misma como la forma en la que éstos aparezcan presentados o localizados en su portal.</p>
                <p>ENLACES: En el caso de que en nombre del dominio se dispusiesen enlaces o hipervínculos hacía otros sitios de Internet, ABSCISA Ingeniería Geomática y Topográfica no ejercerá ningún tipo de control sobre dichos sitios y contenidos. En ningún caso ABSCISA Ingeniería Geomática y Topográfica asumirá responsabilidad alguna por los contenidos de algún enlace perteneciente a un sitio web ajeno, ni garantizará la disponibilidad técnica, calidad, fiabilidad, exactitud, amplitud, veracidad, validez y constitucionalidad de cualquier material o información contenida en ninguno de dichos hipervínculos u otros sitios de Internet. Igualmente la inclusión de estas conexiones externas no implicará ningún tipo de asociación, fusión o participación con las entidades conectadas.</p>
                <p>DERECHO DE EXCLUSIÓN: ABSCISA Ingeniería Geomática y Topográfica se reserva el derecho a denegar o retirar el acceso a portal y/o los servicios ofrecidos sin necesidad de preaviso, a instancia propia o de un tercero, a aquellos usuarios que incumplan las presentes Condiciones Generales de Uso.</p>
                <p>GENERALIDADES: ABSCISA Ingeniería Geomática y Topográfica perseguirá el incumplimiento de las presentes condiciones así como cualquier utilización indebida de su portal ejerciendo todas las acciones civiles y penales que le puedan corresponder en derecho.</p>
                <p>MODIFICACIÓN DE LAS PRESENTES CONDICIONES Y DURACIÓN: ABSCISA Ingeniería Geomática y Topográfica podrá modificar en cualquier momento las condiciones aquí determinadas, siendo debidamente publicadas como aquí aparecen. La vigencia de las citadas condiciones irá en función de su exposición y estarán vigentes hasta que sean modificadas por otras debidamente publicadas.</p>
                <p>LEGISLACIÓN APLICABLE Y JURISDICCIÓN: La relación entre ABSCISA Ingeniería Geomática y Topográfica y el USUARIO se regirá por la normativa española vigente y cualquier controversia se someterá a los Juzgados</p>
            </div>
        </>
    )
}

export default Privacy